name = "savoiardi"
version = "2.0.4"
target = "javascript"
description = "Three.js bindings for Gleam - part of the tiramisu game engine ecosystem"
repository = { type = "github", user = "renatillas", repo = "savoiardi" }
licenses = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
vec = ">= 3.0.1 and < 4.0.0"
quaterni = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
